### PR TITLE
Update for amqplib v2.6

### PR DESCRIPTION
**Pull request by tamtamchik**
Some adjustments for latest amqplib version. Also I think it should bump version of this repo.

Qusetion: **was this repo abandoned?**

### CODE REVIEW

**Comment by videlalvaro** [comment]
@tamtamchik I don't develop it anymore but I do merge PRs

**Comment by tamtamchik** [comment]
@videlalvaro ok then :+1: glad to hear! Thanks for merge!

**Comment by tamtamchik** [comment]
BTW, can you, please, bump the version on packagist?

**Comment by videlalvaro** [comment]
bumped

**Comment by tamtamchik** [comment]
@videlalvaro thanks!

**Pull request merged**
