### PR TITLE
Small features added

### PR DESCRIPTION
**Pull request by sasha-ch**
1. Ability to call  
$RpcClient->initClient()->addRequest()->getReplies()
multiple times correctly.
2. RpcClient::setTimeout()

### CODE REVIEW

**Comment by videlalvaro** [comment]
I think your workaround solves the issue, but, isn't the actual issue that getReplies() doesn't reset the `requests` and `replies` variables?

**Comment by sasha-ch** [comment]
Hello.
Sorry for the long delay in replying.
1. If we use RpcClient multiple times in long-playing script, original behavior produces memory leaks and difficulties with debugging. 
2. I am going to extend "setTimeout" feature. Are you interested in merging it to your lib?

**Comment by videlalvaro** [comment]
yes, are you going with two PRs or everything into this one?

**Comment by sasha-ch** [comment]
Let's working here.

**Comment by sasha-ch** [comment]
Hello.
It is another small fix about lib behavior while callback passed to BaseConsumer::setCallback. is invalid (for example it is protected function of some object).
Origin code returns NULL silently in RpcServer.php:72.
New code throw exception before server start.

**Comment by sasha-ch** [comment]
Thanks!

**Pull request merged**
